name: main

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup
        run: sh setup/setup.sh

      - name: test
        run: ./.github/scripts/test.sh
        shell: sh
