name: main

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: apt
        run: sudo apt install openmpi-bin libopenmpi-dev libscalapack-openmpi-dev

      - name: pip
        run: |
          python3 -m pip install -U pip
          python3 -m pip install numpy scipy toml

      - name: setup
        run: sh setup/setup.sh

      - name: test
        run: ./.github/scripts/test.sh
        shell: sh
